# Generated by Django 5.0.4 on 2024-05-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeConfirmation',
        ),
    ]
