# Generated by Django 5.0.4 on 2024-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_maqola_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='tag',
            field=models.CharField(choices=[('world', 'world'), ('local', 'local'), ('sport', 'sport')], max_length=10),
        ),
    ]
