# Generated by Django 5.0.4 on 2024-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_maqola_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='image',
            field=models.ImageField(default=-1, upload_to=''),
            preserve_default=False,
        ),
    ]
