# Generated by Django 5.1.7 on 2025-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_maqola_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='tag',
            field=models.CharField(choices=[('home', 'home'), ('local', 'local'), ('our_service', 'our_service')], max_length=15),
        ),
    ]
